### ISSUE TITLE
Attempting to build the solution results in an error

### ISSUE THREAD

**Issue by FuckingStealingNames** [rtkzboss/CrimeBoss#1]
Followed the steps in the readme, and when I try to build it, it results in this error:

Unable to instantiate module 'AkAudio': System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\NICK\Documents\Unreal Projects\CrimeBoss-master\Plugins\Wwise\ThirdParty\x64_vc170\Profile\bin'.	

I don't know what's going on.

**Comment by rtkzboss** [comment]
Resolved https://discord.com/channels/1067809091046613002/1233067026054910043/1256382259213369396
